// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3jiJCyU6lcgBdTu1QyIjfebG-NfoXZAA',
    appId: '1:191546183606:web:e3a9e477d95c734faefb17',
    messagingSenderId: '191546183606',
    projectId: 'better-buzz',
    authDomain: 'better-buzz.firebaseapp.com',
    databaseURL: 'https://better-buzz-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'better-buzz.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA25bqoGiVXsjeDU8Tu9KHDdoYQqAC3Gec',
    appId: '1:191546183606:android:e75345a6109f1911aefb17',
    messagingSenderId: '191546183606',
    projectId: 'better-buzz',
    databaseURL: 'https://better-buzz-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'better-buzz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARl35O9rTbJ3OyWExekdt1oe-HpPwbQKg',
    appId: '1:191546183606:ios:ced0f74107c99800aefb17',
    messagingSenderId: '191546183606',
    projectId: 'better-buzz',
    databaseURL: 'https://better-buzz-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'better-buzz.appspot.com',
    iosClientId: '191546183606-m6b0tbti86cd9a2l32vbkdunnqb8c4hf.apps.googleusercontent.com',
    iosBundleId: 'com.example.betterBuzz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARl35O9rTbJ3OyWExekdt1oe-HpPwbQKg',
    appId: '1:191546183606:ios:6f0e5847c643e6ddaefb17',
    messagingSenderId: '191546183606',
    projectId: 'better-buzz',
    databaseURL: 'https://better-buzz-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'better-buzz.appspot.com',
    iosClientId: '191546183606-uv57b1kp6d9bhk707on06vbgc2ekqpcr.apps.googleusercontent.com',
    iosBundleId: 'com.example.betterBuzz.RunnerTests',
  );
}
